<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Ventajas-de-la-reducción-de-dimensiones" data-toc-modified-id="Ventajas-de-la-reducción-de-dimensiones-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Ventajas de la reducción de dimensiones</a></span></li><li><span><a href="#¿Qué-es-la-maldición-de-la-dimensionalidad?" data-toc-modified-id="¿Qué-es-la-maldición-de-la-dimensionalidad?-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>¿Qué es la maldición de la dimensionalidad?</a></span></li><li><span><a href="#Técnicas-de-reducción-del-número-de-variables" data-toc-modified-id="Técnicas-de-reducción-del-número-de-variables-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Técnicas de reducción del número de variables</a></span><ul class="toc-item"><li><span><a href="#Técnicas-de-selección-de-variables" data-toc-modified-id="Técnicas-de-selección-de-variables-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Técnicas de selección de variables</a></span><ul class="toc-item"><li><span><a href="#Filtro-de-baja-varianza" data-toc-modified-id="Filtro-de-baja-varianza-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>Filtro de baja varianza</a></span></li><li><span><a href="#Selección-de-variables-univariadas" data-toc-modified-id="Selección-de-variables-univariadas-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>Selección de variables univariadas</a></span><ul class="toc-item"><li><span><a href="#SelectKBest" data-toc-modified-id="SelectKBest-3.1.2.1"><span class="toc-item-num">3.1.2.1&nbsp;&nbsp;</span>SelectKBest</a></span></li><li><span><a href="#SelectPercentile" data-toc-modified-id="SelectPercentile-3.1.2.2"><span class="toc-item-num">3.1.2.2&nbsp;&nbsp;</span>SelectPercentile</a></span></li><li><span><a href="#SelectFpr" data-toc-modified-id="SelectFpr-3.1.2.3"><span class="toc-item-num">3.1.2.3&nbsp;&nbsp;</span>SelectFpr</a></span></li><li><span><a href="#SelectFdr" data-toc-modified-id="SelectFdr-3.1.2.4"><span class="toc-item-num">3.1.2.4&nbsp;&nbsp;</span>SelectFdr</a></span></li><li><span><a href="#SelectFwe" data-toc-modified-id="SelectFwe-3.1.2.5"><span class="toc-item-num">3.1.2.5&nbsp;&nbsp;</span>SelectFwe</a></span></li><li><span><a href="#GenericUnivariateSelect" data-toc-modified-id="GenericUnivariateSelect-3.1.2.6"><span class="toc-item-num">3.1.2.6&nbsp;&nbsp;</span>GenericUnivariateSelect</a></span></li></ul></li><li><span><a href="#Eliminación-de-características-de-forma-recursiva" data-toc-modified-id="Eliminación-de-características-de-forma-recursiva-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>Eliminación de características de forma recursiva</a></span></li><li><span><a href="#Selección-de-características-basadas-en-árboles" data-toc-modified-id="Selección-de-características-basadas-en-árboles-3.1.4"><span class="toc-item-num">3.1.4&nbsp;&nbsp;</span>Selección de características basadas en árboles</a></span></li></ul></li><li><span><a href="#Técnicas-de-reducción-de-dimensionalidad" data-toc-modified-id="Técnicas-de-reducción-de-dimensionalidad-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Técnicas de reducción de dimensionalidad</a></span><ul class="toc-item"><li><span><a href="#Análisis-de-componentes-principales-(PCA)" data-toc-modified-id="Análisis-de-componentes-principales-(PCA)-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Análisis de componentes principales (PCA)</a></span></li><li><span><a href="#Análisis-de-discriminante-lineal-(LDA)" data-toc-modified-id="Análisis-de-discriminante-lineal-(LDA)-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Análisis de discriminante lineal (LDA)</a></span></li></ul></li></ul></li></ul></div>

La reducción de la dimensionalidad es una de las técnicas básicas de preprocesado de datos, que consiste en la reducción del número de variables.

# Ventajas de la reducción de dimensiones

A priori, puede parecer que cuanta más información, mejor. Sin embargo, en la mayoría de los casos no es así. De hecho, hay varias razones por las que puede ser interesante tratar de reducir el número de dimensiones del conjunto de datos:
- Se reduce la complejidad, con lo que el modelo y sus resultados se hacen más fácilmente interpretables.
- Por razones de ahorro, tanto en coste como en tiempo. Reduciendo las dimensiones, se mejora el rendimiento computacional.
- Se identifican y eliminan las variables irrelevantes, reduciendo el ruido del dataset original. Es importante tener en cuenta que, en ocasiones, el mejor modelo posible no es el que tiene en cuenta más variables, sino aquel que incluye únicamente la información "de calidad". Aquí entra en juego la *Maldición de la dimensionalidad*.


# ¿Qué es la maldición de la dimensionalidad?

Normalmente, un modelo de Machine Learning requiere una información abundante al principio, con el fin de realizar predicciones más precisas. Sin embargo, llegado a cierto punto, el rendimiento del modelo disminuirá conforme aumente el número de variables. Este fenómeno es lo que se conoce como "maldición de la dimensionalidad”.

La maldición de la dimensionalidad tiene lugar porque, al aumentar el número de variables y mantenerse el mismo número de muestras, la densidad de la muestra disminuye exponencialmente, volviéndose cada vez más dispersa. A partir de una muestra dispersa, el modelo de Machine Learning posiblemente obtendrá una solución que, aparentemente, sea muy buena. Sin embargo, lo que estará sucediendo en realidad es que se habrá producido un sobreajuste. 

# Técnicas de reducción del número de variables

En líneas generales, se puede establecer la siguiente clasificación de técnicas de reducción del número de variables:
- Selección de variables: filtro de baja varianza, pruebas estadísticas univariadas, eliminación de características de forma recursiva, bosques aleatorios, ratio de valores faltantes, filtro de alta correlación,  etc.
- Reducción de dimensionalidad:
    - Lineal: análisis factorial, análisis de componentes principales (PCA), análisis de discriminante lineal.
    - No lineal: escala multidimensional, mapeo de características isométricas, etc.


## Técnicas de selección de variables

### Filtro de baja varianza
Elimina las variables cuya varianza no alcanza un cierto umbral. De forma predeterminada, descarta todas las características de varianza cero, es decir, las características que tienen el mismo valor en todas las muestras. 


In [1]:
from sklearn.feature_selection import VarianceThreshold

In [2]:
X = [[0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1]]

In [9]:
np.array(X)

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 1],
       [0, 1, 0],
       [0, 1, 1]])

In [3]:
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))

In [4]:
sel_fit = sel.fit(X)
results = sel_fit.transform(X)
results

array([[0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1]])

In [5]:
results = sel.fit(X).transform(X)
results

array([[0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1]])

In [7]:
results = sel.fit_transform(X)
results

array([[0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1]])

### Selección de variables univariadas

Estas técnicas seleccionan las mejores variables basándose en pruebas estadísticas univariadas. Toman como entrada una función de puntuación que, en general, puede ser:
- Para tareas de regresión: f_regression, mutual_info_regression
- Para tareas de clasificación: chi2, f_classif, mutual_info_classif

#### SelectKBest
Elimina todo menos las k características con puntuaciones más altas.

In [11]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [12]:
X, y = load_iris(return_X_y=True)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
X_new = SelectKBest(chi2, k=2).fit_transform(X, y)
X_new

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.4, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

#### SelectPercentile
Elimina todas las características excepto el porcentaje de variables (especificado por el usuario) que tengan puntuación más alta.

In [14]:
from sklearn.datasets import load_digits

In [17]:
from sklearn.feature_selection import SelectPercentile, chi2

In [15]:
X, y = load_digits(return_X_y=True)

In [19]:
X.shape

(1797, 64)

In [18]:
X_new = SelectPercentile(chi2, percentile=10).fit_transform(X, y)
X_new

array([[ 8.,  5.,  8., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ..., 16.,  0.,  0.],
       [ 0.,  1.,  8., ..., 16.,  5.,  9.],
       ...,
       [ 0.,  0.,  9., ..., 14.,  0.,  0.],
       [ 4.,  0.,  5., ...,  0.,  2.,  0.],
       [ 0.,  0., 12., ...,  6.,  8.,  1.]])

In [20]:
X_new.shape

(1797, 7)

#### SelectFpr
Tasa de falsos positivos.

#### SelectFdr
Tasa de descubrimiento falso.

#### SelectFwe
Error familiar.

#### GenericUnivariateSelect
Realiza una selección de características univariadas con una estrategia configurable.

In [21]:
from sklearn.datasets import load_breast_cancer

In [23]:
from sklearn.feature_selection import GenericUnivariateSelect, chi2

In [22]:
X, y = load_breast_cancer(return_X_y=True)

In [24]:
X.shape

(569, 30)

In [25]:
transformer = GenericUnivariateSelect(chi2, mode='k_best', param=20)

In [26]:
X_new = transformer.fit_transform(X, y)
X_new.shape

(569, 20)

**Nota**
Si los datos son dispersos (sparse), las funciones *chi2, mutual_info_regression* y *mutual_info_classif* responderán bien. 

### Eliminación de características de forma recursiva

Esta técnica consiste en seleccionar grupos de características cada vez más pequeños. Primero, se entrena un estimador con todas las variables y se obtiene la importancia de cada una de ellas. Después, las menos importantes se eliminan y se vuelve a repetir el procedimiento hasta que se alcanza el número deseado de variables finales.  

### Selección de características basadas en árboles

Los árboles de decisión se pueden utilizar para calcular la importancia de las variables, por lo que se pueden usar para descartar variables irrelevantes (combinando el estimador basado en árboles de decisión con el método SelectFromModel de Scikit Learn, por ejemplo.

## Técnicas de reducción de dimensionalidad

### Análisis de componentes principales (PCA)

In [10]:
from sklearn import datasets
from sklearn.decomposition import PCA

In [7]:
X, y = datasets.load_iris(return_X_y=True)

In [8]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
pca = PCA(n_components=3, random_state=10)

In [13]:
pca.fit(X)

PCA(n_components=3, random_state=10)

In [14]:
pca.components_

array([[ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ],
       [ 0.65658877,  0.73016143, -0.17337266, -0.07548102],
       [-0.58202985,  0.59791083,  0.07623608,  0.54583143]])

In [15]:
pca.explained_variance_

array([4.22824171, 0.24267075, 0.0782095 ])

In [16]:
pca.explained_variance_ratio_

array([0.92461872, 0.05306648, 0.01710261])

In [17]:
pca.singular_values_

array([25.09996044,  6.01314738,  3.41368064])

In [18]:
pca.n_features_

4

In [19]:
pca.n_components_

3

In [22]:
X = pca.transform(X)

In [23]:
X

array([[-2.68412563,  0.31939725, -0.02791483],
       [-2.71414169, -0.17700123, -0.21046427],
       [-2.88899057, -0.14494943,  0.01790026],
       [-2.74534286, -0.31829898,  0.03155937],
       [-2.72871654,  0.32675451,  0.09007924],
       [-2.28085963,  0.74133045,  0.16867766],
       [-2.82053775, -0.08946138,  0.25789216],
       [-2.62614497,  0.16338496, -0.02187932],
       [-2.88638273, -0.57831175,  0.02075957],
       [-2.6727558 , -0.11377425, -0.19763272],
       [-2.50694709,  0.6450689 , -0.07531801],
       [-2.61275523,  0.01472994,  0.10215026],
       [-2.78610927, -0.235112  , -0.20684443],
       [-3.22380374, -0.51139459,  0.06129967],
       [-2.64475039,  1.17876464, -0.15162752],
       [-2.38603903,  1.33806233,  0.2777769 ],
       [-2.62352788,  0.81067951,  0.13818323],
       [-2.64829671,  0.31184914,  0.02666832],
       [-2.19982032,  0.87283904, -0.12030552],
       [-2.5879864 ,  0.51356031,  0.21366517],
       [-2.31025622,  0.39134594, -0.239

### Análisis de discriminante lineal (LDA)

https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.LinearDiscriminantAnalysis.html
    
https://scikit-learn.org/stable/modules/lda_qda.html#lda-qda